version: "3.9"

services:
  account:
    build: 
      context: account
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - '8081:8081'

  med_delivery:
    build: 
      context: med-delivery
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - '8080:8080'
  
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: med_delivery_app_db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./local_folder:/data/db
